version: 2

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - hack
    - helpers
    - internal/cache
    - internal/renameio
    - internal/robustio
    - test/testdata_etc

linters-settings:
  staticcheck:
    
    checks: ["all", "-ST1005"]
  govet:
    check-shadowing: false
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - misspell
    - staticcheck
    - stylecheck
    - whitespace
    - unused
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck